const addons = [
  {
    serial: "A1",
    name: "Foyer and hallway protection",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a2.png",
    detail: "The ram board will be used to protect the existing flooring in the foyer and hallway areas.",
    price: "0",
    isChecked: false,
  },
  {
    serial: "A2",
    name: "Flooring materials",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a1.png",
    detail: "The flooring materials, including T-molding or reducer, will be provided by the client and need to be delivered to the site to coordinate with the renovation schedule.",
    price: "-520",
    isChecked: false,
  },
  {
    serial: "A3",
    name: "Resurfacing of ensuite bathroom",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a3.png",
    detail: "Demolish all the existing tiled walls and resurface it with drywall in the ensuite bathroom.",
    price: "1260",
    isChecked: false,
  },
  {
    serial: "A4",
    name: "Resurfacing of main bathroom",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a4.png",
    detail: "Demolish all the existing tiled walls and resurface it with drywall in the main bathroom.",
    price: "1260",
    isChecked: false,
  },
  {
    serial: "A5",
    name: "Custom wall unit",
    image: " ",
    detail: "Supply and install a wall unit in the living area that matches the style of the cabinets in the kitchen area. ",
    price: "8130",
    isChecked: false,
  },
  {
    serial: "A6",
    name: "Dimmable under-cabinet lighting",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a6.png",
    detail: "Supply and install dimmable under-cabinet lighting, including electrical rough-in.",
    price: "570",
    isChecked: false,
  },
  {
    serial: "A7",
    name: "Extra tile backsplash",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a7.png",
    detail: "Supply and install tile backsplash in the stove area which matches the standard style.",
    price: "570",
    isChecked: false,
  },
  {
    serial: "A8",
    name: "Existing lighting wiring remodification",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a8.png",
    detail: "Remodify existing lighting wiring to be hidden and relocate the switches in the kitchen area.",
    price: "3130",
    isChecked: false,
  },
  {
    serial: "A9",
    name: "Kitchen island countertop overhang",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a9.png",
    detail: "Supply and install island countertop to be extended 8”-10” approximately as overhang in the kitchen area.",
    price: "0",
    isChecked: false,
  },
  {
    serial: "A10",
    name: "Pantry",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a10.png",
    detail: "Supply and install a pantry that matches the style of the cabinets in the kitchen area.",
    price: "540",
    isChecked: false,
  },
]

