const addons = [
  {
    serial: "A1",
    name: "Foyer and hallway protection",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a2.png",
    detail: "The ram board will be used to protect the existing flooring in the foyer and hallway areas.",
    price: "0",
    isChecked: false,
  },
  {
    serial: "A2",
    name: "Flooring materials",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a1.png",
    detail: "The flooring materials, including T-molding or reducer, will be provided by the client and need to be delivered to the site to coordinate with the renovation schedule.",
    price: "-520",
    isChecked: false,
  },
  {
    serial: "A3",
    name: "Resurfacing of ensuite bathroom",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a3.png",
    detail: "Demolish all the existing tiled walls and resurface it with drywall in the ensuite bathroom.",
    price: "1260",
    isChecked: false,
  },
  {
    serial: "A4",
    name: "Resurfacing of main bathroom",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a4.png",
    detail: "Demolish all the existing tiled walls and resurface it with drywall in the main bathroom.",
    price: "1260",
    isChecked: false,
  },
  {
    serial: "A5",
    name: "Custom wall unit",
    image: " ",
    detail: "Supply and install a wall unit in the living area that matches the style of the cabinets in the kitchen area. ",
    price: "8130",
    isChecked: false,
  },
  {
    serial: "A6",
    name: "Dimmable under-cabinet lighting",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a6.png",
    detail: "Supply and install dimmable under-cabinet lighting, including electrical rough-in.",
    price: "570",
    isChecked: false,
  },
  {
    serial: "A7",
    name: "Extra tile backsplash",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a7.png",
    detail: "Supply and install tile backsplash in the stove area which matches the standard style.",
    price: "570",
    isChecked: false,
  },
  {
    serial: "A8",
    name: "Existing lighting wiring remodification",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a8.png",
    detail: "Remodify existing lighting wiring to be hidden and relocate the switches in the kitchen area.",
    price: "3130",
    isChecked: false,
  },
  {
    serial: "A9",
    name: "Kitchen island countertop overhang",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a9.png",
    detail: "Supply and install island countertop to be extended 8”-10” approximately as overhang in the kitchen area.",
    price: "0",
    isChecked: false,
  },
  {
    serial: "A10",
    name: "Pantry",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a10.png",
    detail: "Supply and install a pantry that matches the style of the cabinets in the kitchen area.",
    price: "540",
    isChecked: false,
  },
  {
    serial: "A11",
    name: "Floor heating",
    image: "",
    detail: "Supply and install a flooring heating system in the ensuite bathroom common area.",
    price: "2190",
    isChecked: false,
  },
  {
    serial: "A12",
    name: "Floor heating",
    image: "",
    detail: "Supply and install a flooring heating system in the main bathroom common area.",
    price: "2190",
    isChecked: false,
  },
  {
    serial: "A13",
    name: "Ensuite bathroom niche",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a13.png",
    detail: "Supply and install a niche in the ensuite bathroom bathtub area.",
    price: "760",
    isChecked: false,
  },
  {
    serial: "A14",
    name: "Main bathroom niche",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a13.png",
    detail: "Supply and install a niche in the main bathroom shower area.",
    price: "760",
    isChecked: false,
  },
  {
    serial: "A15",
    name: "Fixed glass panel above bathtub",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a15.png",
    detail: "Supply and install a fixed glass panel above the bathtub in the ensuite bathroom area.",
    price: "1510",
    isChecked: false,
  },
  {
    serial: "A16",
    name: "Sliding glass doors above bathtub",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a16.png",
    detail: "Supply and install a set of sliding glass doors above the bathtub in the ensuite bathroom area.",
    price: "1940",
    isChecked: false,
  },
  {
    serial: "A17",
    name: "Oval-shaped countertop overhang",
    image: "",
    detail: "Add an oval-shaped countertop overhang with double edge to the kitchen island.",
    price: "260",
    isChecked: false,
  },
  {
    serial: "A18",
    name: "Vanity with drawer",
    image: "",
    detail: "Supply and install a vanity that features a drawer located at the bottom in both bathrooms.",
    price: "220",
    isChecked: false,
  },
  {
    serial: "A19",
    name: "Medicine cabinet in ensuite bathroom",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a19.png",
    detail: "Supply and install a medicine cabinet in the ensuite bathroom that features double mirrored doors.",
    price: "500",
    isChecked: false,
  },
  {
    serial: "A20",
    name: "Medicine cabinet in main bathroom",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a19.png",
    detail: "Supply and install a medicine cabinet with double mirrored doors in the main bathroom.",
    price: "500",
    isChecked: false,
  },
  {
    serial: "A21",
    name: "Backsplash upgrade",
    image: "../../data-final/addons/20240412-340Watson-Gaetan/a21.png",
    detail: "Upgrade the kitchen area with 12” x 24” white tiles instead of standard subway tiles.",
    price: "220",
    isChecked: false,
  },
]

