const addons = [
  {
    serial: "A1",
    name: "Extra floor tile removal",
    image: "../../data-final/addons/20240405-20EdgecliffGolfway-Rania/a1.jpg",
    detail: "Remove the floor tile in both Foyer and Hallway areas.",
    price: "380",
    isChecked: false,
  },
  {
    serial: "A2",
    name: "Kitchen remodification",
    image: "../../data-final/addons/20240405-20EdgecliffGolfway-Rania/a2.jpg",
    detail: "Demolish the walls marked in red on the floor plan to create an open concept in the kitchen area. Constructing a bulkhead to install 4 pot lights in the kitchen ceiling area.",
    price: "5630",
    isChecked: false,
  },
  {
    serial: "A3",
    name: "Exhaust fan remodification ",
    image: "../../data-final/addons/20240405-20EdgecliffGolfway-Rania/a3.jpg",
    detail: "Remodify hood fan connection in the kitchen area. ",
    price: "1630",
    isChecked: false,
  },
  {
    serial: "A4",
    name: "Laundry doors",
    image: "../../data-final/addons/20240405-20EdgecliffGolfway-Rania/a5.jpg",
    detail: "Remodify laundry opening, replace the existing door with two 30” x 80” bifold doors.",
    price: "2770",
    isChecked: false,
  },
  {
    serial: "A5",
    name: "Painting in kitchen area",
    image: "../../data-final/addons/20240405-20EdgecliffGolfway-Rania/a6.jpg",
    detail: "Benjamin Moore 0C-122 Cotton Balls.",
    price: "0",
    isChecked: false,
  },
  {
    serial: "A6",
    name: "Kitchen Island",
    image: "../../data-final/addons/20240405-20EdgecliffGolfway-Rania/a7.jpg",
    detail: "Adding kitchen island with 3 base cabinets which has 57 ½” width in total.",
    price: "3190",
    isChecked: false,
  },
  {
    serial: "A7",
    name: "Dishwasher",
    image: " ",
    detail: "Plumbing and electrical work only",
    price: "390",
    isChecked: false,
  },
  {
    serial: "A8",
    name: "Bathroom Walls & Shower Base",
    image: "",
    detail: "",
    price: "800",
    isChecked: false,
  },
]

