const kitchenDmItem = [
  "Cabinetry",
  "Countertop",
  "Backsplash",
  "Faucet",
  "Sink",
  "Vinyl Floor",
  "Laminate Floor",
  "Floor Tile",
  "Baseboard",
  "Valance Light",
  "Ceiling Light",
  "Partition Wall",
  "Kitchen door With frame",
  "Dining door With frame"
];

const applianceItem = [
  "Disconnect",
  "Remove and Dispose",
  "Reconnect",
  "Installation",
  "Add 120V Receptacle",
  "Add 240V Receptacle",
]

const bathDmItem = [
  "Vanity",
  "Vanity Sink",
  "Vanity Faucet",
  "Vanity Mirror",
  "Vanity Light",
  "Toilet",
  "Bathtub",
  "Tub Filler",
  "Shower Faucet",
  "Shower Base",
  "Wall Tile",
  "Floor Tile",
  "Baseboard",
  "Medicine Cabinet",
  "Wall Cabinet",
  "Towel Bar",
  "Toilet Paper Holder",
  "Soap Dish"
];

const powderDmItem = [
  "Vanity",
  "Vanity Sink",
  "Vanity Faucet",
  "Vanity Mirror",
  "Vanity Light",
  "Toilet",
  "Wall Tile",
  "Floor Tile",
  "Baseboard",
  "Medicine Cabinet",
  "Wall Cabinet",
  "Towel Bar",
  "Toilet Paper Holder"
]

const floorDmItem = [
  "Laminate Floor",
  "Vinyl Floor",
  "Hardwood Floor",
  "Carpet",
  "Floor Tile",
  "Baseboard",
  "Shoemold"
];

const kitchenItem = [
  "Kitchen Cabinet Material",
  "Kitchen Cabinet Installation",
  "Cabinet Handle Material",
  "Cabinet Handle Installation",
  "Countertop Material",
  "Countertop Installation",
  "Countertop & Overhang Material",
  "Countertop & Overhang Installation",
  "Countertop Waterfall Material",
  "Countertop Waterfall Installation",
  "Backspalsh Material",
  "Backaplash Installation",
  "Kitchen Faucet Material",
  "Kitchen Faucet Installation",
  "Kitchen Sink Material",
  "Kitchen Sink Installation",
  "Floor Tile Material",
  "Floor Tile Installation",
  "Vinyl Floor Material",
  "Vinyl Floor Installation",
  "Laminate Floor Material",
  "Laminate Floor Installation",
  "Baseboard Material",
  "Baseboard Installation",
  "Shoemold Material",
  "Shoemold Installation",
  "Cabinet Valance Light Material",
  "Cabinet Valance Light Installation",
  "Wall Paint",
  "Ceiling Paint",
  "Door Paint",
  "Door Opening Finishing",
  "Drop Ceiling",
  "Potlight Material",
  "Potlight Installation"
]

const bathItem = [
  "Vanity Cabinet Material",
  "Vanity Cabinet Installation",
  "Vanity Cabinet Handle Material",
  "Vanity Cabinet Handle Installation",
  "Vanity sink Material",
  "Vanity sink Installation",
  "Vanity faucet Material",
  "Vanity faucet Installation",
  "Vanity mirror Material",
  "Vanity mirror Installation",
  "Vanity light Material",
  "Vanity light Installation",
  "Toilet Material",
  "Toilet Installation",
  "Bathtub Material",
  "Bathtub Installation",
  "Tub Filler Material",
  "Tub Filler Installation",
  "Shower Faucet Material",
  "Shower Faucet Installation",
  "Shower Base Material",
  "Shower Base Installation",
  "Shower Enclosure Material",
  "Shower Enclosure Installation",
  "Wall Tile Material",
  "Wall Tile Installation",
  "Floor Tile Material",
  "Floor Tile Installation",
  "Baseboard Material",
  "Baseboard Installation",
  "Shoemold Material",
  "Shoemold Installation",
  "Wall Paint",
  "Ceiling Paint",
  "Door Paint",
  "Medicine Cabinet Material",
  "Medicine Cabinet Installation",
  "Wall Cabinet Material",
  "Wall Cabinet Installation",
  "Grab Bar Material",
  "Grab Bar Installation",
  "Towel Bar Material",
  "Towel Bar Installation",
  "Toilet Paper Holder Material",
  "Toilet Paper Holder Installation"
]

const powderItem = [
  "Vanity Cabinet Material",
  "Vanity Cabinet Installation",
  "Vanity Cabinet Handle Material",
  "Vanity Cabinet Handle Installation",
  "Vanity sink Material",
  "Vanity sink Installation",
  "Vanity faucet Material",
  "Vanity faucet Installation",
  "Vanity mirror Material",
  "Vanity mirror Installation",
  "Vanity light Material",
  "Vanity light Installation",
  "Toilet Material",
  "Toilet Installation",
  "Wall Tile Material",
  "Wall Tile Installation",
  "Floor Tile Material",
  "Floor Tile Installation",
  "Baseboard Material",
  "Baseboard Installation",
  "Wall Paint",
  "Ceiling Paint",
  "Door Paint",
  "Medicine Cabinet Material",
  "Medicine Cabinet Installation",
  "Wall Cabinet Material",
  "Wall Cabinet Installation",
  "Grab Bar Material",
  "Grab Bar Installation",
  "Towel Bar Material",
  "Towel Bar Installation",
  "Toilet Paper Holder Material",
  "Toilet Paper Holder Installation"
]

const floorItem = [
  "Laminate Floor Material",
  "Laminate Floor Installation",
  "Vinyl Floor Material",
  "Vinyl Floor Installation",
  "Hardwood Floor Material",
  "Hardwood Floor Installation",
  "Floor Tile Material",
  "Floor Tile Installation",
  "Underlayment Material",
  "Underlayment Installation",
  "Carpet Material",
  "Carpet Installation",
  "Baseboard Material",
  "Baseboard Installatioon",
  "Shoemold Material",
  "Shoemold Installation"
]

const paintItem = [
  "Wall Touch Up",
  "Wall Paint",
  "Baseboard/Shoemold Paint",
  "Closet Interior Paint",
  "Closet Shelf/Rod Remove and Reinstall",
  "Walk-in Closet Shelf/Rod Remove and Reinstall",
  "Walk-in Closet Interior Paint",
  "Interior Door Paint",
  "Ceiling Touch up",
  "Ceiling Stucco Remove",
  "Ceiling Stucco Reapir",
  "Ceiling Paint"
]


const otherItem = [
  "Closet Sliding Door Material",
  "Closet Sliding Door Installation",
  "Ceiling Light Material",
  "Ceiling Light Installation",
  "Demolish Partition Wall",
  "Modify Lighting Electrical Box Location",
  "Build Drywall Bulkhead and Paint Finishing",
  "Replace Switch/Outlet with Plate",
]


