const addons = [
  {
    serial: "A1",
    name: "Site protection",
    image: "../../data-final/addons/20240729-3131bridletowne-Paul/a1.png",
    detail: "All necessary site protection and dust control are required since the client will be residing on-site during the construction period.",
    price: "1610",
    isChecked: false,
  },
  {
    serial: "A2",
    name: "Custom-sized shaker-style cabinets",
    image: "../../data-final/addons/20240729-3131bridletowne-Paul/a2.png",
    detail: "Supply and install custom-sized shaker-style cabinets to meet the kitchen design based on the actual on-site dimensions.",
    price: "2400",
    isChecked: false,
  },
  {
    serial: "A3",
    name: "Full-height backsplash",
    image: "",
    detail: "Add a full height backsplash with the same countertop material in the kitchen area.",
    price: "2340",
    isChecked: false,
  },
  {
    serial: "A4",
    name: "Under-cabinet lights",
    image: "../../data-final/addons/20240729-3131bridletowne-Paul/a4.png",
    detail: "Electrical rough-in and finish for under-cabinet light fixtures, materials will be provided by Renu My Condo..",
    price: "1210",
    isChecked: false,
  },
  {
    serial: "A5",
    name: "Waste bin",
    image: "../../data-final/addons/20240729-3131bridletowne-Paul/a5.png",
    detail: "",
    price: "340",
    isChecked: false,
  },
  {
    serial: "A6",
    name: "Vinyl flooring",
    image: "../../data-final/addons/20240729-3131bridletowne-Paul/a6.png",
    detail: "Supply and install vinyl flooring in the kitchen, foyer, and foyer closet areas on top of the existing tile flooring.",
    price: "3420",
    isChecked: false,
  },
  {
    serial: "A7",
    name: "Floor tile",
    image: "",
    detail: "Supply and install floor tile in the kitchen, foyer, and foyer closet areas.",
    price: "9480",
    isChecked: false,
  },
]