const addons = [
  {
    serial: "A1",
    name: "Floor tile to vinyl flooring",
    image: "../../data-final/addons/20240703-1hycrest-Suzanne/a1.png",
    detail: "Replacing floor tile with vinyl flooring in both dining and kitchen areas.",
    price: "2820",
    isChecked: false,
  },
  {
    serial: "A2",
    name: "Kitchen remodification",
    image: "",
    detail: "Remodifying walls, electrical rough-ins and finishes in the kitchen area.",
    price: "3510",
    isChecked: false,
  },
  {
    serial: "A3",
    name: "Existing floor tile replacement",
    image: "",
    detail: "Replacing the existing floor tiles with RENU floor tiles in foyer, laundry and closet in the hall area.",
    price: "2890",
    isChecked: false,
  },
  {
    serial: "A4",
    name: "Bathtub to shower room",
    image: "",
    detail: "Convert the bathtub to a shower room in the ensuite bathroom.",
    price: "3000",
    isChecked: false,
  },
  {
    serial: "A5",
    name: "Ceiling smoothing",
    image: "",
    detail: "Convert all the popcorn ceilings to flat ceilings throughout the unit.",
    price: "7500",
    isChecked: false,
  },
  {
    serial: "A6",
    name: "Kitchen cabinets",
    image: "",
    detail: "Supply and install both base and wall cabinets in high gloss white material, including cabinet modifications.",
    price: "2400",
    isChecked: false,
  },
  {
    serial: "A7",
    name: "Countertop overhang",
    image: "",
    detail: "Extend the countertop by 8-10 inches in the kitchen area.",
    price: "400",
    isChecked: false,
  },
  {
    serial: "A8",
    name: "Under-cabinet light fixture",
    image: "",
    detail: "Supply and install under-cabinet light fixtures in the kitchen area, including new electrical wiring. ",
    price: "950",
    isChecked: false,
  },
  {
    serial: "A9",
    name: "Thermostats replacement",
    image: "",
    detail: "Replace two existing thermostats in both dining and living areas, items will be provided by the client. ",
    price: "TBD",
    isChecked: false,
  },
  {
    serial: "A10",
    name: "Ceiling light relocating",
    image: "",
    detail: "Relocate the ceiling light in the dining area, the exact location will be confirmed on site. ",
    price: "920",
    isChecked: false,
  },
  {
    serial: "A11",
    name: "Light fixtures installation",
    image: "",
    detail: "Install a total of 10 light fixtures throughout the unit, fixtures will be provided by the client, the specific installation price depends on the specs of all the light fixtures.",
    price: "TBD",
    isChecked: false,
  },
  
]