const addons = [
  {
    serial: "A1",
    name: "Flooring upgrade",
    image: "../../data-final/addons/20240703-1hycrest-Suzanne/a1.png",
    detail: "Upgrade the flooring from laminate to vinyl, materials and installation will both be provided by Renu My Condo.",
    price: "2000",
    isChecked: false,
  },
  {
    serial: "A2",
    name: "Existing floor tile replacement",
    image: "../../data-final/addons/20240703-1hycrest-Suzanne/a2.png",
    detail: "Replacing the existing floor tiles with Renu My Condo floor tiles in foyer, laundry and closet in the hall area.",
    price: "2360",
    isChecked: false,
  },
  {
    serial: "A3",
    name: "Ceiling smoothing",
    image: "../../data-final/addons/20240703-1hycrest-Suzanne/a3.png",
    detail: "Convert all the popcorn ceilings to flat ceilings throughout the unit.",
    price: "7500",
    isChecked: false,
  },
  {
    serial: "A4",
    name: "Kitchen remodification",
    image: "../../data-final/addons/20240703-1hycrest-Suzanne/a4.png",
    detail: "Remodifying walls, electrical rough-ins and finishes in the kitchen area.",
    price: "3510",
    isChecked: false,
  },
  {
    serial: "A5",
    name: "Kitchen cabinets",
    image: "../../data-final/addons/20240703-1hycrest-Suzanne/a5.png",
    detail: "Supply and install both base and wall cabinets in high gloss white material, including cabinet modifications.",
    price: "2850",
    isChecked: false,
  },
  {
    serial: "A6",
    name: "Under-cabinet light fixture",
    image: "../../data-final/addons/20240703-1hycrest-Suzanne/a6.png",
    detail: "Supply and install under-cabinet light fixtures in the kitchen area, including new electrical wiring. ",
    price: "950",
    isChecked: false,
  },
  {
    serial: "A7",
    name: "Ceiling light relocating",
    image: "../../data-final/addons/20240703-1hycrest-Suzanne/a7.png",
    detail: "Relocate the ceiling light in the dining area, the exact location will be confirmed on site.",
    price: "920",
    isChecked: false,
  },
  {
    serial: "A8",
    name: "Light fixtures installation",
    image: "",
    detail: "Install a total of 10 light fixtures throughout the unit, fixtures will be provided by the client, the specific installation price depends on the specs of all the light fixtures.",
    price: "TBD",
    isChecked: false,
  },
  {
    serial: "A9",
    name: "Thermostats replacement ",
    image: "",
    detail: "Replace two existing thermostats in both dining and living areas, items will be provided by the client. ",
    price: "TBD",
    isChecked: false,
  },
]