const addons = [
  {
    serial: "A1",
    name: "Full-height backsplash ",
    image: "../../data-final/addons/20240724-88corporate-Kerry/a1.png",
    detail: "Add a full height backsplash with the same countertop material in the kitchen area.",
    price: "1870",
    isChecked: false,
  },
  {
    serial: "A2",
    name: "Remodification of the kitchen area",
    image: "../../data-final/addons/20240724-88corporate-Kerry/a2.png",
    detail: "Remodify kitchen range hood exhaust duct. Install a bulkhead after existing ceiling light fixture is removed. Relocate the power outlets for the stove and range hood. Additional cabinets, countertop, full-height backsplash, and Lazy Susan system included.",
    price: "4930",
    isChecked: false,
  },
  {
    serial: "A3",
    name: "Ceiling light remodification ",
    image: "",
    detail: "Remodify existing ceiling for track light electrical rough-in and finishing in the kitchen area.",
    price: "2010",
    isChecked: false,
  },
  {
    serial: "A4",
    name: "Under-cabinet strip light",
    image: "../../data-final/addons/20240724-88corporate-Kerry/a4.png",
    detail: "Supply and install under-cabinet light strip in the kitchen area.",
    price: "870",
    isChecked: false,
  },
  {
    serial: "A5",
    name: "Kitchen floor tile",
    image: "../../data-final/addons/20240724-88corporate-Kerry/a5.png",
    detail: "Supply and install floor tile in the kitchen area.",
    price: "2130",
    isChecked: false,
  },
  {
    serial: "A6",
    name: "Trims in the kitchen entrance area",
    image: "../../data-final/addons/20240724-88corporate-Kerry/a6.png",
    detail: "Supply and install casing and jamb made of the same material as the baseboard at the entrance to the kitchen.",
    price: "670",
    isChecked: false,
  },
  {
    serial: "A7",
    name: "Light fixtures installation",
    image: "",
    detail: "Install a total of 3 light fixtures throughout the unit, fixtures will be provided by the client, the specific installation price depends on the specs of all the light fixtures.",
    price: "TBD",
    isChecked: false,
  },
]